### PR TITLE
Explicitly select PHP 8.0 in CI

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by phil-davis** [comment]
https://travis-ci.com/github/sabre-io/sabre-tzserver/jobs/457153942
```
$ php --version

PHP 8.0.0 (cli) (built: Dec  7 2020 13:24:49) ( ZTS )

Copyright (c) The PHP Group

Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies

    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies

    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans

$ composer --version

Composer version 2.0.8 2020-12-03 17:20:38

before_script.1

0.18s$ if [ $RUN_PHPCSFIXER == "FALSE" ]; then composer remove --no-update --dev friendsofphp/php-cs-fixer; fi
before_script.2

7.28s$ composer update $PREFER_LOWEST

0.00s$ if [ $RUN_PHPCSFIXER == "TRUE" ]; then php vendor/bin/php-cs-fixer fix --dry-run --diff; fi

The command "if [ $RUN_PHPCSFIXER == "TRUE" ]; then php vendor/bin/php-cs-fixer fix --dry-run --diff; fi" exited with 0.

0.11s$ if [ $RUN_PHPUNIT == "TRUE" ]; then php vendor/bin/phpunit --configuration tests/phpunit.xml $WITH_COVERAGE; fi

PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.

Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

...                                                                 3 / 3 (100%)

Time: 00:00.006, Memory: 6.00 MB

OK (3 tests, 3 assertions)
```

Great stuff - the real PHP 8.0 is working on Travis now.

**Comment by evert** [comment]
@phil-davis this repo might as well get retired /archived. It was never finished to a completed product.

**Comment by phil-davis** [comment]
@evert or @staabm feel free to archive.
I don't have privs to see the Settings tab, to do "Archive this repository"

**Comment by evert** [comment]
K will do. I think I can also unarchive so if @staabm disagrees Im happy to revert this.

**Pull request merged**
